name: Presubmit

on: [pull_request]

jobs:
  build-desktop:
    name: build-desktop
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/google/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
      - name: Test Google Cloud upload
        run: |
          WORKFLOW_OS=`echo \`uname\` | sed "s/Darwin/mac/" | tr [:upper:] [:lower:]`
          source build/$WORKFLOW_OS/install_gcloud_sdk.sh
          gcloud --version
          gsutil --version
          echo $GCLOUD_KEY_BASE64 | base64 --decode > "$HOME/gcloud-key.json"
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          echo "Hello, world" > test-${WORKFLOW_OS}.txt
          gsutil cp test-${WORKFLOW_OS}.txt gs://filament-build/
      - name: Run build script
        run: |
          WORKFLOW_OS=`echo \`uname\` | sed "s/Darwin/mac/" | tr [:upper:] [:lower:]`
          cd build/$WORKFLOW_OS && ./build.sh ${TARGET}
        env:
          TARGET: presubmit

  build-windows:
    name: build-windows
    runs-on: windows-latest

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init %GITHUB_WORKSPACE%
          cd %GITHUB_WORKSPACE%
          git remote add origin https://github.com/google/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +%GITHUB_REF%:%GITHUB_REF:refs/=refs/remote/%
          git checkout --progress --force %GITHUB_REF:refs/=refs/remote/%
      - name: Run build script
        run: |
          build\windows\build-github.bat

  build-android:
    name: build-android
    runs-on: macos-latest

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/google/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
      - name: Run build script
        run: |
          cd build/android && ./build.sh ${TARGET}
        env:
          TARGET: presubmit

  build-ios:
    name: build-iOS
    runs-on: macos-latest

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/google/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
      - name: Run build script
        run: |
          cd build/ios && ./build.sh ${TARGET}
        env:
          TARGET: presubmit

  build-web:
    name: build-web
    runs-on: macos-latest

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/google/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
      - name: Run build script
        run: |
          cd build/web && ./build.sh ${TARGET}
        env:
          TARGET: presubmit
